events {
    worker_connections 1024;
}

http {
    upstream minio {
        server minio:9000;
    }

    # Настройка кэша
    proxy_cache_path /var/cache/nginx/minio levels=1:2 keys_zone=minio_cache:10m max_size=1g inactive=60m use_temp_path=off;

    server {
        listen 80;

        location ~ ^/reports/(.*) {
            # Кэширование для статических файлов
            proxy_cache minio_cache;
            proxy_cache_valid 200 1h;  # Кэшировать успешные ответы на 1 час
            proxy_cache_valid 404 1m;  # Кэшировать 404 на 1 минуту
            add_header X-Cache-Status $upstream_cache_status;  # Добавляем заголовок для отладки

            # Переписываем URI, добавляя 'reports/' к пути
            rewrite ^/reports/(.*)$ /reports/$1 break;
            # Проксируем запрос к MinIO
            proxy_pass http://minio;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}